ALTER TABLE goals
    ADD CONSTRAINT goals_id_user_id_unique UNIQUE (id, user_id);

CREATE TABLE daily_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    goal_id BIGINT,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    task_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    xp_reward INTEGER NOT NULL DEFAULT 10,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT daily_tasks_goal_owner_fk
        FOREIGN KEY (goal_id, user_id) REFERENCES goals (id, user_id) ON DELETE CASCADE,
    CONSTRAINT daily_tasks_status_check
        CHECK (status IN ('PENDING', 'COMPLETED', 'SKIPPED')),
    CONSTRAINT daily_tasks_source_check
        CHECK (source IN ('MANUAL', 'AI_RECOMMENDED')),
    CONSTRAINT daily_tasks_title_not_blank
        CHECK (length(btrim(title)) > 0),
    CONSTRAINT daily_tasks_xp_reward_check
        CHECK (xp_reward > 0)
);

CREATE INDEX daily_tasks_user_id_task_date_idx
    ON daily_tasks (user_id, task_date);
CREATE INDEX daily_tasks_goal_id_idx
    ON daily_tasks (goal_id);

CREATE TABLE task_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL UNIQUE REFERENCES daily_tasks (id) ON DELETE CASCADE,
    xp_awarded INTEGER NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_completions_xp_awarded_check
        CHECK (xp_awarded > 0)
);

CREATE TABLE character_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users (id) ON DELETE CASCADE,
    level INTEGER NOT NULL DEFAULT 1,
    total_xp BIGINT NOT NULL DEFAULT 0,
    strength INTEGER NOT NULL DEFAULT 1,
    vitality INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT character_profiles_level_check CHECK (level >= 1),
    CONSTRAINT character_profiles_total_xp_check CHECK (total_xp >= 0),
    CONSTRAINT character_profiles_strength_check CHECK (strength >= 1),
    CONSTRAINT character_profiles_vitality_check CHECK (vitality >= 1)
);

CREATE TABLE boss_raids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage INTEGER NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    required_level INTEGER NOT NULL DEFAULT 1,
    max_hp INTEGER NOT NULL,
    xp_reward INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT boss_raids_stage_check CHECK (stage >= 1),
    CONSTRAINT boss_raids_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT boss_raids_required_level_check CHECK (required_level >= 1),
    CONSTRAINT boss_raids_max_hp_check CHECK (max_hp > 0),
    CONSTRAINT boss_raids_xp_reward_check CHECK (xp_reward > 0)
);

CREATE TABLE raid_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    boss_raid_id BIGINT NOT NULL REFERENCES boss_raids (id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    damage_dealt INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT raid_attempts_status_check
        CHECK (status IN ('IN_PROGRESS', 'VICTORY', 'DEFEAT')),
    CONSTRAINT raid_attempts_damage_dealt_check
        CHECK (damage_dealt >= 0),
    CONSTRAINT raid_attempts_completion_check
        CHECK (
            (status = 'IN_PROGRESS' AND completed_at IS NULL)
            OR (status IN ('VICTORY', 'DEFEAT') AND completed_at IS NOT NULL)
        )
);

CREATE INDEX raid_attempts_user_id_started_at_idx
    ON raid_attempts (user_id, started_at);
CREATE INDEX raid_attempts_boss_raid_id_idx
    ON raid_attempts (boss_raid_id);
