CREATE TABLE weekly_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    goal_id BIGINT,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    week_start_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    source VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    xp_reward INTEGER NOT NULL DEFAULT 75,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT weekly_quests_goal_owner_fk
        FOREIGN KEY (goal_id, user_id) REFERENCES goals (id, user_id) ON DELETE CASCADE,
    CONSTRAINT weekly_quests_status_check
        CHECK (status IN ('PENDING', 'COMPLETED', 'SKIPPED')),
    CONSTRAINT weekly_quests_source_check
        CHECK (source IN ('MANUAL', 'SYSTEM')),
    CONSTRAINT weekly_quests_title_not_blank
        CHECK (length(btrim(title)) > 0),
    CONSTRAINT weekly_quests_xp_reward_check
        CHECK (xp_reward > 0)
);

CREATE INDEX weekly_quests_user_id_week_start_date_idx
    ON weekly_quests (user_id, week_start_date);
CREATE INDEX weekly_quests_goal_id_idx
    ON weekly_quests (goal_id);

CREATE TABLE weekly_quest_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_quest_id BIGINT NOT NULL UNIQUE REFERENCES weekly_quests (id) ON DELETE CASCADE,
    xp_awarded INTEGER NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT weekly_quest_completions_xp_awarded_check
        CHECK (xp_awarded > 0)
);
