CREATE TABLE recommendation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    goal_id BIGINT NOT NULL,
    created_task_id BIGINT REFERENCES daily_tasks (id) ON DELETE SET NULL,
    provider VARCHAR(50) NOT NULL,
    action VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    task_date DATE NOT NULL,
    xp_reward INTEGER NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'AI_RECOMMENDED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT recommendation_history_goal_owner_fk
        FOREIGN KEY (goal_id, user_id) REFERENCES goals (id, user_id) ON DELETE CASCADE,
    CONSTRAINT recommendation_history_action_check
        CHECK (action IN ('PREVIEWED', 'ACCEPTED')),
    CONSTRAINT recommendation_history_source_check
        CHECK (source IN ('AI_RECOMMENDED')),
    CONSTRAINT recommendation_history_title_not_blank
        CHECK (length(btrim(title)) > 0),
    CONSTRAINT recommendation_history_xp_reward_check
        CHECK (xp_reward > 0)
);

CREATE INDEX recommendation_history_user_goal_created_at_idx
    ON recommendation_history (user_id, goal_id, created_at DESC);
