CREATE TABLE character_progression_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users (id) ON DELETE CASCADE,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    xp_awarded INTEGER NOT NULL,
    total_xp BIGINT NOT NULL,
    level INTEGER NOT NULL,
    strength INTEGER NOT NULL,
    vitality INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT character_progression_events_source_type_check
        CHECK (source_type IN ('DAILY_TASK', 'WEEKLY_QUEST', 'BOSS_RAID')),
    CONSTRAINT character_progression_events_xp_awarded_check CHECK (xp_awarded > 0),
    CONSTRAINT character_progression_events_total_xp_check CHECK (total_xp >= 0),
    CONSTRAINT character_progression_events_level_check CHECK (level >= 1),
    CONSTRAINT character_progression_events_strength_check CHECK (strength >= 1),
    CONSTRAINT character_progression_events_vitality_check CHECK (vitality >= 1)
);

CREATE INDEX character_progression_events_user_id_created_at_idx
    ON character_progression_events (user_id, created_at DESC, id DESC);

CREATE INDEX character_progression_events_user_id_source_idx
    ON character_progression_events (user_id, source_type, source_id);
