spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5434/questlog
    username: questlog
    password: questlog
    driver-class-name: org.postgresql.Driver
  application:
    name: quest-log-be

server:
  port: 8081
